name: Build and Deploy to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Use .NET Core 8.0

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build the Application
        run: dotnet build --configuration Release --no-restore

      - name: Publish the Application
        run: dotnet publish -c Release -o ./publish_output

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cicddemo' # Azure Web App name
          slot-name: 'production' # Use 'production' slot
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./publish_output

# Notes:
# 1. Replace 'AZURE_WEBAPP_PUBLISH_PROFILE' with the publish profile secret of your Azure Web App.
# 2. To set the secret, go to your GitHub repository > Settings > Secrets and Variables > Actions > New repository secret.
# 3. Paste the content of your Azure publish profile (cicddemo.PublishSettings) as the value for the secret.
